applications:
    - configs:
        CONFIG_ENV: production
        NODE_ENV: production
        PORT: "8080"
      containerPort: 8080
      image: 160569206162.dkr.ecr.us-east-1.amazonaws.com/heroes-live-on
      imageTag: v4
      name: main
      replicas: 2
      route:
        enabled: false
      secrets:
        - name: global-config
          path: heroes-live-on/config-global
        - name: env-config
          path: heroes-live-on/config
        - name: rds-config
          path: heroes-live-on/config-rds
      serviceType: NodePort
      type: server
    - containerPort: 80
      image: 160569206162.dkr.ecr.us-east-1.amazonaws.com/helo-super-admin
      imageTag: v13
      name: superadmin
      replicas: 1
      route:
        certificate:
            enabled: true
            secretName: heroes-tls
        enabled: true
        host: super-admin.heroes-live-on.com
        path: /
      type: client
    - containerPort: 80
      image: 160569206162.dkr.ecr.us-east-1.amazonaws.com/helo-main-client
      imageTag: v12
      name: main
      replicas: 1
      route:
        certificate:
            enabled: true
            secretName: heroes-tls
        enabled: true
        host: heroes-live-on.com
        path: /
      type: client
    - containerPort: 80
      image: 160569206162.dkr.ecr.us-east-1.amazonaws.com/helo-admin
      imageTag: v12
      name: admin
      replicas: 1
      route:
        certificate:
            enabled: true
            secretName: heroes-tls
        enabled: true
        host: admin.heroes-live-on.com
        path: /
      type: client
awsRegion: us-east-1
environment: production
projectName: heroes-live-on
