applications:
    - configs:
        NODE_ENV: staging
      containerPort: 8080
      image: 160569206162.dkr.ecr.eu-central-1.amazonaws.com/tokens-main-server
      imageTag: v2
      name: main
      replicas: 1
      route:
        enabled: false
      runAsRoot: true
      secrets:
        - name: staging
          path: tokens/staging
      serviceType: NodePort
      type: server
    - containerPort: 80
      image: 160569206162.dkr.ecr.eu-central-1.amazonaws.com/tokens-main-client
      imageTag: v1
      name: main
      replicas: 1
      route:
        certificate:
            enabled: false
        enabled: true
        host: tokens.staging.apps.cluster.carmel6000.org
        path: /
      type: client
awsRegion: eu-central-1
environment: staging
projectName: tokens
